import './globals.css'

export const metadata = {
  title: 'PWA App',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon-192x192.png',
    shortcut: '/icon-192x192.png',
    apple: '/apple-touch-icon-180x180.png'
  },
  applicationName: 'PWA App',
  manifest: '/manifest.json',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        {children}</body>
    </html>
  )
}

